import { readFileSync, readdirSync } from 'node:fs';
import { join, resolve } from 'node:path';

import { describe, expect, it } from 'vitest';

import { injectRuntimeIntoDocument } from '../../reference/src/wrap.js';
import { startPackageServer } from '../../reference/src/node-serve.js';
import { checkCardDocument, checkCardPackage } from '../src/static-checks.js';

/**
 * The retained single-file examples are checked here; current package examples are checked below.
 *
 * They are the first cards most people will ever open, so they are held to the
 * rules the specification asks of any card — and a page that shows off a format
 * while shipping a card that fails its own checker would be the worst possible
 * advertisement for it.
 *
 * The files are generated by `docs/examples/build-legacy.mjs` through the reference
 * export pipeline; this suite checks what actually ships, not the generator.
 */

// Resolved from the project root rather than from import.meta.url: under the
// jsdom test environment the global URL resolves a relative specifier against
// the fake page origin, not against this file.
const EXAMPLES_DIR = resolve(process.cwd(), 'docs/examples');

/**
 * A budget per card rather than one number for all three, because the cards do
 * not carry the same kind of weight: the two with artwork inline the picture as
 * a data URI so the card stays openable on its own, and the one without artwork
 * has no excuse for growing at all.
 *
 * Every card must appear here. An unlisted file fails rather than falling back
 * to a default — a new card's size should be a decision somebody made, not a
 * number it inherits by turning up.
 */
const SITE_CARD_BUDGETS = Object.freeze({
  'weather.card.html': 122880,
  'note.card.html': 122880,
  'piano.card.html': 34816,
});

const EXPECTED_CARD_COUNT = 3;

const cardFiles = readdirSync(EXAMPLES_DIR)
  .filter((name) => name.endsWith('.card.html'))
  .sort();

describe('the legacy single-file card examples', () => {
  it(`ships at least ${EXPECTED_CARD_COUNT} of them`, () => {
    expect(cardFiles.length).toBeGreaterThanOrEqual(EXPECTED_CARD_COUNT);
  });

  for (const name of cardFiles) {
    describe(name, () => {
      const source = readFileSync(join(EXAMPLES_DIR, name), 'utf8');

      it('passes the section 9.3 static checks with no error', () => {
        const { findings } = checkCardDocument(source);
        const errors = findings.filter((finding) => finding.level === 'error');
        // The findings themselves go into the failure message: a bare count
        // tells whoever broke it that something is wrong, not what.
        expect(errors, JSON.stringify(errors, null, 2)).toEqual([]);
      });

      it('has a budget of its own and stays within it', () => {
        const budget = SITE_CARD_BUDGETS[name];
        expect(budget, `${name} has no entry in SITE_CARD_BUDGETS`).toBeTypeOf('number');
        expect(Buffer.byteLength(source)).toBeLessThanOrEqual(budget);
      });

      // Only the style blocks: the rest of the file is markup and a base64
      // picture, and a rule scanner turned loose on either finds nothing but
      // spends a long time not finding it.
      const styles = [...source.matchAll(/<style\b[^>]*>([\s\S]*?)<\/style>/g)]
        .map((match) => match[1])
        .join('\n');

      /**
       * Section 1.7 forbids an unconditional viewport height: a card sized by
       * its content would report a height no lower than its frame, the frame
       * would grow to match, and the two would push each other up with neither
       * able to come back down.
       */
      it('never declares a viewport height unconditionally', () => {
        const offenders = styles
          .split('\n')
          .map((line, at) => ({ line: line.trim(), at: at + 1 }))
          .filter(({ line }) => /\b\d*\.?\d+(vh|dvh|svh|lvh)\b/.test(line))
          .filter(({ line }) => !line.includes('data-card-sizing="viewport"'));
        expect(offenders, JSON.stringify(offenders, null, 2)).toEqual([]);
      });

      /**
       * The other half of the same clause: a card may fill and clip its frame,
       * but only once a host has said the frame is what decides the height. So
       * any rule that fills or clips the document itself has to name that mark.
       */
      it('gates filling and clipping behind the viewport sizing regime', () => {
        for (const rule of styles.matchAll(/([^{}]*)\{([^{}]*)\}/g)) {
          const [, selector, body] = rule;
          const clipsOrFills =
            /(^|[^-])height:\s*100%/.test(body) || /overflow:\s*hidden/.test(body);
          const isDocumentLevel = /(^|[\s,>])(html|body)(\s|,|$)/.test(selector);
          if (clipsOrFills && isDocumentLevel) {
            expect(selector, `this rule fills or clips the document unconditionally: ${selector.trim()}`)
              .toContain('data-card-sizing="viewport"');
          }
        }
      });
    });
  }
});

/**
 * The row that frames them, on the page rather than in the cards.
 *
 * A card cannot see the frame it sits in, so "no scrollbar appears inside" is a
 * promise the page has to keep from the outside: one height for all three, and
 * frames that are not allowed to scroll. The heights themselves are checked by
 * arithmetic over the cards' fixed bands, not here.
 */
describe('the live card row on the front page', () => {
  const page = readFileSync(resolve(process.cwd(), 'docs/index.html'), 'utf8');
  const iframes = [...page.matchAll(/<iframe\b[^>]*>/g)].map((match) => match[0]);

  it('frames every example card', () => {
    expect(iframes).toHaveLength(EXPECTED_CARD_COUNT);
  });

  it('gives all three the same height', () => {
    // One declaration, and none of them carries a height of its own: that is
    // what makes the three equal rather than three numbers that happen to match.
    const declarations = [...page.matchAll(/\.cards iframe\s*\{[^}]*\}/g)]
      .flatMap((rule) => [...rule[0].matchAll(/(?:^|[^-])height:\s*([^;]+);/g)].map((m) => m[1].trim()));
    expect(declarations).toEqual(['420px']);
    for (const iframe of iframes) {
      expect(iframe).not.toMatch(/\bheight\s*=/);
      expect(iframe).not.toMatch(/style="[^"]*height/);
    }
  });

  it('does not let a frame scroll', () => {
    for (const iframe of iframes) {
      expect(iframe).toContain('scrolling="no"');
    }
  });
});

/**
 * `weather-package/` is the site's example of the current package shape
 * (section 1.1): a directory, an `index.html` that carries no injected
 * runtime of its own (that only ever happens at serve time — the whole
 * point of "the disk keeps only what the author wrote"), and a real
 * `assets/` with a stylesheet and a picture referenced by ordinary relative
 * path rather than inlined as a data URI. The other three examples on this
 * page predate the package redefinition and are kept as the degenerate-
 * package shape (section 6.2); this is the newer shape's example.
 */
describe('the package-shaped example (weather-package/)', () => {
  const packageDir = join(EXAMPLES_DIR, 'weather-package');
  const files = new Map([
    ['index.html', readFileSync(join(packageDir, 'index.html'), 'utf8')],
    ['assets/style.css', readFileSync(join(packageDir, 'assets/style.css'), 'utf8')],
    ['assets/hero.webp', readFileSync(join(packageDir, 'assets/hero.webp'))],
  ]);

  it('passes the section 9.3 static checks with no error', () => {
    const { findings } = checkCardPackage(files);
    const errors = findings.filter((finding) => finding.level === 'error');
    expect(errors, JSON.stringify(errors, null, 2)).toEqual([]);
  });

  it('carries no injected runtime on disk: the shim only ever arrives at serve time', () => {
    expect(files.get('index.html')).not.toContain('showcard reference injection layer');
  });

  it('round-trips through the reference host: served for real, loaded for real', async () => {
    const server = await startPackageServer({ injectEntry: injectRuntimeIntoDocument });
    try {
      server.packageHost.mount('site-example-weather-package', { files });

      const entryResponse = await fetch(server.url('site-example-weather-package', 'index.html'));
      expect(entryResponse.status).toBe(200);
      const entryText = await entryResponse.text();
      expect(entryText).toContain('window.card');

      const cssResponse = await fetch(server.url('site-example-weather-package', 'assets/style.css'));
      expect(cssResponse.status).toBe(200);
      expect(await cssResponse.text()).toBe(files.get('assets/style.css'));

      const heroResponse = await fetch(server.url('site-example-weather-package', 'assets/hero.webp'));
      expect(heroResponse.status).toBe(200);
      expect(Number(heroResponse.headers.get('content-length'))).toBe(files.get('assets/hero.webp').length);
    } finally {
      await server.close();
    }
  });
});
